### ISSUE TITLE
Cannot change department affiliation

### ISSUE THREAD

**Issue by elena1114** [cristianbravolillo/EPP-CMU-Thesis#4]
Hi, I am new to Latex and I am having trouble locating where I can change department affiliation to non-EPP. Thank you! This template is a life saver!

**Comment by cristianbravolillo** [comment]
Hi! It was not possible to easily change the affiliation, so I just created a new command to do just that.

In `content/frontmatter.tex`, after the `author` command, add your affiliation, like this:

```tex
\author{John Doe}
\affiliation{Electrical Engineering}
```

Compile again, and you should see the change in the first page.

Good luck!

**Comment by elena1114** [comment]
Thank you!!!!
